# Generated by Django 4.1.7 on 2023-03-31 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_date', models.DateTimeField(auto_now_add=True)),
                ('commande_prix', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livreur_nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('livreur_prenom', models.CharField(max_length=50, verbose_name='Prénom')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_libelle', models.CharField(max_length=128)),
                ('produit_prix', models.FloatField(default=0.0)),
                ('produit_type', models.CharField(choices=[('PS', 'Pinsa'), ('AP', 'Antipasti'), ('PA', 'Pasta'), ('PF', "Past'al forno"), ('DS', 'Dessert'), ('BS', 'Boisson')], max_length=2)),
                ('produit_sous_type', models.CharField(choices=[('BQ', 'Basique'), ('SP', 'Spéciale'), ('VG', 'Végétarienne')], max_length=2, null=True)),
                ('produit_composition', models.TextField(max_length=1000, null=True)),
                ('produit_photo', models.ImageField(blank=True, null=True, upload_to='plats')),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajet_distance', models.FloatField(default=0)),
                ('trajet_prix', models.FloatField(default=0)),
                ('trajet_depart', models.DateTimeField(auto_now_add=True)),
                ('trajet_livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_quantite', models.IntegerField(default=1)),
                ('detail_notes', models.TextField(max_length=1000, null=True)),
                ('detail_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.commande')),
                ('detail_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.produit')),
            ],
        ),
    ]
